appName: restaurant
imageName: ymandrews/restaurant:0.1.4
replicas: 1
serviceName: restaurant-svc
targetPort: 80
sourcePort: 80
nodePort: 31001
appVersion: 0.1.4
githubUrl: https://api.github.com/users/magladde 

