apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: restaurant
  name: restaurant
spec:
  replicas: 1
  selector:
    matchLabels:
      app: restaurant
  template:
    metadata:
      labels:
        app: restaurant
    spec:
      containers:
        - image: ymandrews/restaurant:0.1.0
          name: restaurant
          env:
            - name: REACT_APP_GITHUB_URL
              value: "https://api.github.com/users/arandomgal"
          ports:
            - containerPort: 80