apiVersion: v1
kind: Service
metadata:
  labels:
    app: restaurant
  name: restaurant-svc
spec:
  ports:
    - name: http
      port: 3000
      protocol: TCP
      targetPort: 3000
      nodePort: 32767
  selector:
    app: restaurant
  type: NodePort