apiVersion: v1
kind: Service
metadata:
  labels:
    app: restaurant
  name: restaurant-svc
spec:
  ports:
    - name: http
      port: 80
      protocol: TCP
      targetPort: 80
      nodePort: 31001
  selector:
    app: restaurant
  type: NodePort