apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: {{.Values.appName}}
  name: {{.Values.appName}}
spec:
  replicas: {{.Values.replicas}}
  selector:
    matchLabels:
      app: {{.Values.appName}}
  template:
    metadata:
      labels:
        app: {{.Values.appName}}
    spec:
      containers:
        - image: {{.Values.imageName}}
          name: {{.Values.appName}}
          env:
            - name: REACT_APP_GITHUB_URL
              value: {{.Values.githubUrl}}
          ports:
            - containerPort: {{.Values.targetPort}}